plugin: amazon.aws.aws_ec2
regions:
  - ap-south-1  # Modify this with the correct region
filters:
  instance-state-name: running  # Filters only running instances
keyed_groups:
  - key: tags.Name
    prefix: tag_Name
  - key: instance_type
    prefix: instance_type
hostnames:
  - tag:Name
  - private_ip
  - public_ip
